Explicitly declare `workspace.package.readme`
This fixes dependabot. Error pasted below:

error: failed to load manifest for workspace member `dependabot_tmp_dir/lib`
referenced by workspace at `dependabot_tmp_dir/Cargo.toml`

Caused by:
  failed to parse manifest at `dependabot_tmp_dir/lib/Cargo.toml`

Caused by:
  error inheriting `readme` from workspace root manifest's `workspace.package.readme`

Caused by:
  `workspace.package.readme` was not defined